### PR TITLE
bump cf-k8s-networking to v0.2.0

### PR DESCRIPTION
**Pull request by kauana**
The cf-k8s-networking team recently switched to Istio 1.6. As a result, Istio is replacing its old "Policy" API with the "PeerAuthentication" API so we must update the kpack Policy config and the generated istio config to reflect this change.

For more context, please see the story in the cf-k8s-networking backlog #172031795.

**Acceptance Criteria**
**Given** I have deployed cf-for-k8s with the branch `istio-upgrade-shared-config`.
**When** I run `istioctl version`
**Then** I can see that control plane and data version plane show version `1.6`
**And**
**When** I describe PeerAuthentication objects with `kubectl describe peerauthentications.security.istio.io -n cf-blobstore`
**Then** I see the `cf-blobstore-allow-plaintext` object.

Tag your pair, your PM, and/or team

@ndhanushkodi @XanderStrike @tcdowney

### CODE REVIEW

**Comment by acosta11** [comment]
I see the CI jobs have passed and after manually installing the branch, I was able to validate the provided A/C. Looks good to me!

Thanks,
Andrew

--------------

A/C Console Output
```
$ istioctl version
client version: 1.5.4
control plane version: df8ea82bf434fece015767579ef2e4a16e6a3fb3-dirty
data plane version: 1.6-dev (26 proxies)
```


```
$ kubectl describe peerauthentications.security.istio.io -n cf-blobstore
Name:         cf-blobstore-allow-plaintext
Namespace:    cf-blobstore
Labels:       kapp.k14s.io/app=1592241866964495000
              kapp.k14s.io/association=v1.f4c9143c9150875876e9b3cd9c822d6c
Annotations:  kapp.k14s.io/identity: v1;cf-blobstore/security.istio.io/PeerAuthentication/cf-blobstore-allow-plaintext;security.istio.io/v1beta1
              kapp.k14s.io/original:
                {"apiVersion":"security.istio.io/v1beta1","kind":"PeerAuthentication","metadata":{"labels":{"kapp.k14s.io/app":"1592241866964495000","kapp...
              kapp.k14s.io/original-diff-md5: c6e94dc94aed3401b5d0f26ed6c0bff3
API Version:  security.istio.io/v1beta1
Kind:         PeerAuthentication
Metadata:
  Creation Timestamp:  2020-06-15T17:26:35Z
  Generation:          1
  Resource Version:    71288
  Self Link:           /apis/security.istio.io/v1beta1/namespaces/cf-blobstore/peerauthentications/cf-blobstore-allow-plaintext
  UID:                 b8f96203-fd62-4f26-b34c-21e848ad5f64
Spec:
  Mtls:
    Mode:  PERMISSIVE
  Selector:
    Match Labels:
      App:  minio
Events:     <none>
```

**Comment by jamespollard8** [comment]
This change breaks cf-for-k8s installation on Kind. Here's what we're seeing:

the symptom appears as:
```
kapp: Error: waiting on reconcile deployment/metric-proxy (apps/v1) namespace: cf-system:
  Finished unsuccessfully (Deployment is not progressing: ProgressDeadlineExceeded (message: ReplicaSet "metric-proxy-8698fb757b" has timed out progressing.))
```
or occasionally as
```
kapp: Error: waiting on reconcile deployment/eirini (apps/v1) namespace: cf-system:
  Finished unsuccessfully (Deployment is not progressing: ProgressDeadlineExceeded (message: ReplicaSet "eirini-78c458d945" has timed out progressing.))
```

Testing this on Kind locally, we found the following logs for why the ingressgateway couldn't stand up:
```
$ k describe pod/istio-ingressgateway-4nksv -n istio-system | tail -n 10
Events:
  Type     Reason       Age                   From                         Message
  ----     ------       ----                  ----                         -------
  Normal   Scheduled    15m                   default-scheduler            Successfully assigned istio-system/istio-ingressgateway-4nksv to kind-control-plane
  Warning  FailedMount  13m                   kubelet, kind-control-plane  Unable to attach or mount volumes: unmounted volumes=[istiod-ca-cert istio-token], unattached volumes=[istiod-ca-cert istio-token podinfo istio-ingressgateway-service-account-token-2p5kp istio-envoy config-volume ingressgateway-certs ingressgatewaysdsudspath ingressgateway-ca-certs]: timed out waiting for the condition
  Warning  FailedMount  11m                   kubelet, kind-control-plane  Unable to attach or mount volumes: unmounted volumes=[istio-token istiod-ca-cert], unattached volumes=[istio-envoy ingressgateway-ca-certs istio-ingressgateway-service-account-token-2p5kp config-volume istio-token ingressgatewaysdsudspath ingressgateway-certs istiod-ca-cert podinfo]: timed out waiting for the condition
  Warning  FailedMount  9m32s (x11 over 15m)  kubelet, kind-control-plane  MountVolume.SetUp failed for volume "istio-token" : failed to fetch token: the API server does not have TokenRequest endpoints enabled
  Warning  FailedMount  9m10s                 kubelet, kind-control-plane  Unable to attach or mount volumes: unmounted volumes=[istio-token istiod-ca-cert], unattached volumes=[config-volume ingressgateway-ca-certs istio-token podinfo istio-envoy ingressgatewaysdsudspath ingressgateway-certs istio-ingressgateway-service-account-token-2p5kp istiod-ca-cert]: timed out waiting for the condition
  Warning  FailedMount  5m28s (x13 over 15m)  kubelet, kind-control-plane  MountVolume.SetUp failed for volume "istiod-ca-cert" : configmap "istio-ca-root-cert" not found
  Warning  FailedMount  7s                    kubelet, kind-control-plane  Unable to attach or mount volumes: unmounted volumes=[istiod-ca-cert istio-token], unattached volumes=[istio-envoy istiod-ca-cert ingressgatewaysdsudspath ingressgateway-certs ingressgateway-ca-certs config-volume istio-ingressgateway-service-account-token-2p5kp istio-token podinfo]: timed out waiting for the condition
```

**Comment by jamespollard8** [comment]
We rely heavily enough on Kind in our pipelines (to test across our supported range of K8s versions) that we'll need to revert this. Once we figure out a plan forward, we can try again for round 2 of this istio/cf-k8s-networking bump PR.

**Comment by jenspinney** [comment]
We can take a look at this. We've created a story in our backlog to investigate what's going on: https://www.pivotaltracker.com/story/show/173346213

**Comment by zankich** [comment]
@jamespollard8 if kind compatibility is required for furthur validation is there a reason why the PR gate is not using a kind deployed k8s cluster?

**Comment by jamespollard8** [comment]
Good callout 👍 . We have plans to add these checks to the PR gate but just haven't prioritized that work yet.

These are already written and are part of the dev>master checks - it shouldn't take much effort for us to add these to the PR checks.

image

**Pull request merged**
