### PR TITLE
allow eirini plaintext communications

### PR DESCRIPTION
**Pull request by cwlbraa**
In the process of removing unnecessary secrets from component releases, we want to change CAPI->eirini communication to be encrypted by istio. To support this, we're opening port 8080 as the plain http port on the OPI deployment.

Story to make this PR: https://www.pivotaltracker.com/story/show/173947341
Story to remove certs: https://www.pivotaltracker.com/story/show/173905990

**EDIT:** after initially pushing, we found out we couldn't do this exclusively additively - OPI can't serve both TLS and plaintext simultaneously. To work around this, we aimed this PR at a branch of capi-k8s-release: https://github.com/cloudfoundry/capi-k8s-release/pull/57 and vendir synced. When this PR is merged, please notify us so we can merge the PR on our side and hope things wash out in the nightly bump!

**Acceptance Steps**
```
kubectl -n cf-system exec -it deployment/cf-api-server -- curl http://eirini.cf-system:8080/apps
```
should return something like: `{"desired_lrp_scheduling_infos":[]}`

@jspawar

### CODE REVIEW

**Comment by cwlbraa** [comment]
When this is merged, we'll merge https://github.com/cloudfoundry/capi-k8s-release/pull/57

**Comment by jamespollard8** [comment]
Looks good to me! @cwlbraa @jspawar looks like you'll need to rebase due to a conflict we've created - sorry about that

**Comment by cwlbraa** [comment]
rebased and resolved!

**Comment by cwlbraa** [comment]
ick, seems like this might not be as additive-only as we thought!

**Comment by jamespollard8** [comment]
Woah - a real smoke test failure!

**Comment by cwlbraa** [comment]
after initially pushing, we found out we couldn't do this exclusively additively - OPI can't serve both TLS and plaintext simultaneously. To work around this, we aimed this PR at a branch of capi-k8s-release: https://github.com/cloudfoundry/capi-k8s-release/pull/57 and vendir synced. When this PR is merged, please notify us so we can merge the PR on our side and hope things wash out in the nightly bump!

**Comment by jamespollard8** [comment]
Cool - looks good to me! Our update-capi pipeline is still paused but we'll plan on unpausing it once you give us the go ahead tomorrow.

**Pull request merged**
