### PR TITLE
Disable Eirini Staging

### PR DESCRIPTION
**Pull request by georgethebeatle**
Signed-off-by: Oleksandr Slynko <oslynko@pivotal.io>
Co-authored-by: Oleksandr Slynko <oslynko@pivotal.io>

## Please take a moment to review the questions before submitting the PR

🚫 We only accept PRs to `develop` branch. If this is an exception, please specify why 🚫

### WHAT is this change about?

We have a new pod in eirini related to staging that we don't need for cf4k8s. This PR switches eirini staging off.

### Please provide any contextual information.

Story about staging: https://www.pivotaltracker.com/story/show/171306745
Story about running aminimal Eirini with cf4k8s: https://www.pivotaltracker.com/story/show/170313550

### Have you read the [contributing guidelines](https://github.com/cloudfoundry/cf-for-k8s/blob/master/.github/contributing.md)?

- [ x ] YES
- [ ] NO

### Does this PR introduce a new ytt library?

- [ ] YES - please specify
- [ x ] NO

### Please provide Acceptance Criteria for this change?

1. Upate eirini chart to this commit: https://github.com/cloudfoundry-incubator/eirini-release/tree/d68fc23335fdbcac449bbf5bf838f540c5eb0317
2. Deployment should succeed

### What is the level of urgency for publishing this change?

- [ ] **Urgent** - unblocks current or future work
- [ x ] **Slightly Less than Urgent**

### Tag your pair, your PM, and/or team!
@julz @alex-slynko @cloudfoundry/eirini

### CODE REVIEW

**Comment by davewalter** [comment]
Hi @georgethebeatle @alex-slynko 

Can you include the Eirini bump with this PR?

We had to revert the last PR that bumped Eirini because vendir was not in sync with the committed changes. For reference, we have a checklist of steps to take before opening a PR [here](https://github.com/cloudfoundry/cf-for-k8s/blob/develop/docs/contributing.md).

Regards,
Dave and @angelachin

**Comment by gdankov** [comment]
Hi @davewalter,

We added a commit which bumps the Eirini version to the latest one as of now (`1.4.0`). We also rebased this branch on top of `develop`. Let us know if there's still anything we missed.

Regards,
Georgi && @schaefm-ibm

**Comment by jamespollard8** [comment]
> We added a commit which bumps the Eirini version to the latest one as of now (`1.4.0`). We also rebased this branch on top of `develop`. Let us know if there's still anything we missed.

Great thanks. We just added a new test (checking for `vendir sync` consistency) that required a small patch from us on `develop` - please rebase once more to go green.

**Comment by gdankov** [comment]
@jamespollard8 Done 🙂 

Looks like the current bot failure is not related to this PR.

**Comment by jenspinney** [comment]
I re-ran the the vendir-sync check and it passed on re-run. We have a chore to make that job less flakey.

**Comment by acosta11** [comment]
Thanks for the PR @georgethebeatle and @alex-slynko ! We went ahead and verified this with a manual deploy and app push since ci did not do so. In the future, submitting the PR from a branch of cf-for-k8s will get the ci verification to run automatically. You all on the Eirini team should have push access on the repo to create such a branch. And if anyone does not have access, let us know so we can fix it.

Thanks,
Andrew and @jenspinney

**Pull request merged**
