### PR TITLE
Add external db check on pr to ci pipeline (second try)

### PR DESCRIPTION
**Pull request by kramerul**
Add a check for external DB functionality to pull request checks in the concourse pipeline (#168)

We could not test this on our concourse. Integrations and configurations for GCP are missing.

Acceptance Steps*
Update Concourse Pipeline and see if new pull request steps are working

See also #291

@lucaschimweg @modulo11

### CODE REVIEW

**Comment by ericpromislow** [comment]
There've been a few rough edges that our pipeline picked up and we've been fixing them in place. Please see recent commits to the develop branch if you're interested.

Also we're wondering about emitting the following info into the logs of a publicly readable pipeline:

From `install-cf-on-gke/task.sh`:
Lines 40-42:

```
 echo "NOTE: the values we're currently not rotating are:"
 cat env-metadata/cf-vars.yaml | yq -r 'keys'
 echo "(we're also not testing rotating our app_registry credentials)"
```

This is just the names of the keys, not the values, correct?

**Comment by kramerul** [comment]
Hi @ericpromislow,

we haven't changed the lines 40-42 in `install-cf-on-gke/task.sh`. They were changed by @Birdrock a month ago.

**Comment by kramerul** [comment]
Just for completeness, these are the [addition changes](https://github.com/cloudfoundry/cf-for-k8s/compare/ed8acf440c4a16499b09657b0b19f64a0f00d962...41bdc93382bf12659eaea4adf1af757abf18f893)

**Comment by Birdrock** [comment]
@ericpromislow It should just be the keys, but we should double check.

**Comment by kramerul** [comment]
Hi @ericpromislow,
I had a look at the changes, you have done to fix our PR.
- **Missing executable test:** After testing everything and opening this PR, we moved the inline bash stuff of `install-postgres` to an extra file. Unfortunately, we never tested this and therefore we missed to set the execution bit
- **Invalid bash syntax:** This is unclear, how this could have happened.
- **Add missing fields:** I'm quite sure, that it was also working without these fields.

We will try to avoid such problems in the future.

**Comment by ericpromislow** [comment]
Hi @kramerul,

We realize there's a higher difficulty in PRing pipeline changes than core code if you don't have access to the pipeline, and certainly appreciate the PR. I wouldn't want you to waste your time building a one-time sandbox, for example, for executing shell scripts in safely.

Thanks for the PR.

**Pull request merged**
