### PR TITLE
Annotate metric-proxy image

### PR DESCRIPTION
**Pull request by heycait**
[#172921741]

Signed-off-by: Louie Brann <lbrann@pivotal.io>

@louis-brann @hev

### CODE REVIEW

**Comment by acosta11** [comment]
Hello,

We docker inspected the provided image reference, but are having trouble finding the deplab labels. The output includes `            "Labels": null` in the Config section where we expected to see the large block of yaml describing the git sha used to build and all of the linux utils in the dockerfile. Would y'all happen to have annotated a different image than the one specified here?

Thanks,
Andrew and @davewalter

**Comment by heycait** [comment]
@acosta11 I think we're a little confused. We ran ` deplab inspect --image oratos/metric-proxy:latest` after running the other `deplap` command and our image and see a bunch of what looks like OSL things.

**Comment by heycait** [comment]
We did it again and think it worked this time.

**Comment by acosta11** [comment]
The giant json blob is there! Looks good!

Thanks,
Andrew and @davewalter

**Pull request merged**
